# Time complexity and numpy

* Searching operation time complexity in list and sets
* Numpy arrays, creation, access, dimensions and shapes
* Operations on numpy arrays, element wise and matrix multiplications

## Summary of list, tuple, set and dict


| Property/ Data Structure | List | Tuple | Set | Dict |
| --- | --- | --- | --- | --- |
| Is it Mutable? | Yes | No  | Yes | Yes |
| Is it Ordered? | Yes | Yes | No  | Yes, as per insertion time |
| Is it Indexed? | Yes | Yes | No  | Using key |
| Can it contain Duplicates? | Yes | Yes | No | Keys cannot be duplicates |
| Is data Hashed while storing?  | No  | No  | Yes | Yes |  
| Search complexity? | O(n)  | O(n) | O(1) | O(1) |

In [47]:
import time
import random

### Searching in lists vs sets/dict


In [48]:
random.randint(0, 10000)

5314

In [49]:
l = [random.randint(0, 2000000) for _ in range(2000000)]
set_a = set(l)
# print(l)

In [50]:
time_start = time.process_time()
if 70000 in l:
    print("Found")
time_end = time.process_time()
time_total_list = time_end - time_start
print("time_total_list = {0: .9f}".format(time_total_list))
# l.index(700)

time_total_list =  0.040695064


In [95]:
time_start = time.process_time()
if 70000 in set_a:
    print("Found")
time_end = time.process_time()
time_total_set = time_end - time_start
print("time_total_set = {0: .9f}".format(time_total_set))

time_total_set =  0.001165829


In [96]:
print("speedup = ", time_total_list/time_total_set)

speedup =  34.90654632884648


## Numpy arrays as faster alternatives to numerical lists

### Creating numpy arrays

In [53]:
import numpy as np

In [54]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
a.size

10

In [56]:
a.shape

(10,)

In [57]:
a.ndim

1

In [58]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [59]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
b = np.zeros_like(a)
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
b = np.ones_like(a)
b

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [62]:
b = np.random.randint(0, 10, size=10)
b

array([5, 5, 2, 6, 6, 2, 4, 3, 5, 7])

In [63]:
type(b)

numpy.ndarray

In [64]:
c = np.zeros((2, 3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
b = np.random.randint(0, 10, size=(2, 4))
b

array([[3, 9, 0, 7],
       [7, 6, 3, 2]])

In [66]:
b = np.identity(4) # for square matrices
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
b = np.eye(4, 3) # for square and rectangular matrices
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

#### Creating from lists

In [68]:
l = [i for i in range(10)]
display(l)
display(type(l))
a = np.array(l)
display(a)
type(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

numpy.ndarray

In [69]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
b = a.reshape((2, 5))
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
b.ndim

2

In [72]:
b.shape

(2, 5)

In [73]:
b.size

10

In [74]:
a = np.arange(6).reshape((2, 3))
a

array([[0, 1, 2],
       [3, 4, 5]])

### Basic operations on numpy arrays

In [75]:
a.sum()

15

In [76]:
a.sum(axis=0)

array([3, 5, 7])

In [77]:
a.sum(axis=1)

array([ 3, 12])

In [78]:
a.min()

0

In [79]:
a.min(axis=0)

array([0, 1, 2])

In [80]:
a.min(axis=1)

array([0, 3])

In [81]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Accessing elements

In [83]:
a = np.arange(10)
a
a[5]

5

In [84]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [85]:
a[0][2]

2

In [86]:
a[0, 2]

2

In [87]:
a = np.arange(5)
display(a)
b = 2*np.ones(5)
display(b)

array([0, 1, 2, 3, 4])

array([2., 2., 2., 2., 2.])

#### Element wise operations

In [88]:
a*b

array([0., 2., 4., 6., 8.])

In [89]:
np.multiply(a, b)

array([0., 2., 4., 6., 8.])

In [90]:
a = 2*np.identity(2)
display(a)
b = np.arange(4).reshape((2, 2))
display(b)

array([[2., 0.],
       [0., 2.]])

array([[0, 1],
       [2, 3]])

#### Matrix operations

In [91]:
np.dot(a, b)

array([[0., 2.],
       [4., 6.]])

#### Stacking arrays

In [92]:
a = np.array([0, 1, 2])
b = np.array([0, -1, -2])
c = np.vstack((a, b))
display(c)

array([[ 0,  1,  2],
       [ 0, -1, -2]])

#### Arrays with random elements

In [93]:
c = np.random.rand(2, 3)
display(c)

array([[0.79091935, 0.84269436, 0.26762844],
       [0.68217338, 0.17838716, 0.56701913]])

In [94]:
d = np.random.randint(0, 100, size=50)
display(d)

array([ 7, 94, 23, 39,  5, 67, 82, 81, 57, 86, 42, 83, 56,  9, 97, 70, 22,
       32,  6, 90, 10, 77, 83, 53, 44, 89, 95, 14, 99, 28, 45, 59, 30,  1,
       58, 46,  8, 61, 40, 27, 26, 27, 38, 15, 52, 15, 54, 99, 73, 84])

## To be continued next time
* Filtering numpy arrays and masking
* Time complexity of mathematical operations between numpy and lists
* Plotting with matplotlib
* Introduction to classes and objects
* Pandas and ML....